name: aigis-dev
services:
  app:
    container_name: aigis-dev
    build:
      context: .
      dockerfile: dockerfile-dev
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env-dev
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started

  mongo:
    container_name: mongo-dev
    image: mongo:4.2.18
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env-dev

  redis:
    container_name: redis-dev
    image: redis:8.0-alpine
    restart: unless-stopped
    volumes:
      - ./data/redis:/data/redis
    ports:
      - 6379:6379
    env_file:
      - .env-dev
